all:
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/devops-key.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    webservers:
      hosts:
        webserver:
          ansible_host: "34.207.116.147"
          private_ip: "172.31.16.182"
    elasticsearch_nodes:
      hosts:
        elasticsearch:
          ansible_host: "52.90.98.35"
          private_ip: "172.31.22.93"
    kibana_nodes:
      hosts:
        kibana:
          ansible_host: "3.95.57.211"
          private_ip: "172.31.26.147"
    database_primary:
      hosts:
        mysql_primary:
          ansible_host: "52.91.58.187"
          private_ip: "172.31.27.236"
    database_standby:
      hosts:
        mysql_standby:
          ansible_host: "34.224.68.79"
          private_ip: "172.31.21.232"
    databases:
      children:
        database_primary:
        database_standby:
