all:
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    webservers:
      hosts:
        webserver:
          ansible_host: "44.213.128.6"
          private_ip: "172.31.10.121"

    elasticsearch_nodes:
      hosts:
        elasticsearch:
          ansible_host: "44.222.94.80"
          private_ip: "172.31.0.45"

    kibana_nodes:
      hosts:
        kibana:
          ansible_host: "34.233.71.251"
          private_ip: "172.31.5.100"

    database_primary:
      hosts:
        mysql_primary:
          ansible_host: "35.153.156.66"
          private_ip: "172.31.10.28"

    database_standby:
      hosts:
        mysql_standby:
          ansible_host: "13.219.244.225"
          private_ip: "172.31.7.59"

    databases:
      children:
        database_primary:
        database_standby:
