all:
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    webservers:
      hosts:
        webserver:
          ansible_host: "18.209.5.250"
          private_ip: "172.31.16.182"

    elasticsearch_nodes:
      hosts:
        elasticsearch:
          ansible_host: "54.175.234.9"
          private_ip: "172.31.22.93"

    kibana_nodes:
      hosts:
        kibana:
          ansible_host: "184.73.18.22"
          private_ip: "172.31.26.147"

    database_primary:
      hosts:
        mysql_primary:
          ansible_host: "3.90.161.197"
          private_ip: "172.31.27.236"

    database_standby:
      hosts:
        mysql_standby:
          ansible_host: "34.229.220.47"
          private_ip: "172.31.21.232"

    databases:
      children:
        database_primary:
        database_standby:
