---
- name: Deploy Sample Web Application
  hosts: webservers
  become: yes
  vars:
    app_name: "devops-sample-app"
    app_version: "1.0.0"
    mysql_host: "{{ hostvars['mysql-primary']['private_ip'] | default('localhost') }}"
    elasticsearch_host: "{{ hostvars['elasticsearch']['private_ip'] | default('localhost') }}"
  roles:
    - webserver

- name: Configure Elasticsearch and Kibana Integration
  hosts: kibana
  become: yes
  vars:
    elasticsearch_host: "{{ hostvars['elasticsearch']['private_ip'] | default('localhost') }}"
  tasks:
    - name: Update Kibana Elasticsearch configuration
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^elasticsearch.hosts:'
        line: 'elasticsearch.hosts: ["http://{{ elasticsearch_host }}:9200"]'
      notify: restart kibana
    - name: Restart Kibana to apply configuration
      systemd:
        name: kibana
        state: restarted
  handlers:
    - name: restart kibana
      systemd:
        name: kibana
        state: restarted

- name: Verify MySQL Replication
  hosts: mysql_standby
  become: yes
  tasks:
    - name: Check replication status
      shell: mysql -u root -pDevOpsPassword123! -e "SHOW SLAVE STATUS\G"
      register: replication_status
    - name: Display replication status
      debug:
        var: replication_status.stdout_lines
