all:
  children:
    webservers:
      hosts:
        webserver:
          ansible_host: "{{ webserver_public_ip | default('127.0.0.1') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    elasticsearch:
      hosts:
        elasticsearch:
          ansible_host: "{{ elasticsearch_public_ip | default('127.0.0.1') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          private_ip: "{{ elasticsearch_private_ip | default('127.0.0.1') }}"
    
    kibana:
      hosts:
        kibana:
          ansible_host: "{{ kibana_public_ip | default('127.0.0.1') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          elasticsearch_ip: "{{ elasticsearch_private_ip | default('127.0.0.1') }}"
    
    mysql_primary:
      hosts:
        mysql-primary:
          ansible_host: "{{ mysql_primary_public_ip | default('127.0.0.1') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          private_ip: "{{ mysql_primary_private_ip | default('127.0.0.1') }}"
    
    mysql_standby:
      hosts:
        mysql-standby:
          ansible_host: "{{ mysql_standby_public_ip | default('127.0.0.1') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          private_ip: "{{ mysql_standby_private_ip | default('127.0.0.1') }}"
          master_ip: "{{ mysql_primary_private_ip | default('127.0.0.1') }}"

  vars:
    ansible_python_interpreter: /usr/bin/python3